# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.1/language-python/ for more details
#
version: 2.1

jobs:
  docker-lint:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch
    #working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      # Download and cache dependencies
      - run:
          name: Install dependencies
          command: |
            make install
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      # run setup to create python virtualenv & source it
      - run:
          name: Run setup
          command: |
            make setup
      # run lint to checks for bugs in a Dockerfile
      - run:
          name: Run lint
          command: |
            . venv/bin/activate
            make lint
  
  docker-build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker image and pust to Docker hub
          command: |
            bash ./run_docker.sh

workflows:
  default:
    jobs:
      - docker-lint
      - docker-build:
          requires: [docker-lint]
