# Python CircleCI 2.1 configuration file
# Check https://circleci.com/docs/2.1/language-python/ for more details
version: 2.1

# An orb for working with Amazon Elastic Container Service for Kubernetes (Amazon EKS)
# Check https://circleci.com/developer/orbs/orb/circleci/aws-eks for more details
orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3

jobs:
  docker-lint:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            make install
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Run setup to create python virtualenv & source it
          command: |
            make setup
      - run:
          name: Run lint to checks for bugs in a Dockerfile
          command: |
            . venv/bin/activate
            make lint
  
  docker-build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker image and pust to Docker hub
          command: |
            bash ./run_docker.sh

  create-cluster:
    description: >
      Creates an EKS cluster and required resources (e.g. VPC) using the eksctl
      tool.
    docker:
      - image: cimg/python:3.7
    parameters:
      cluster-name:
        description: |
          Enter name of the EKS cluster
        type: string
        default: udacity-devpos-capstone-cluster
    steps:
      - checkout
      - install-aws-iam-authenticator:
          release-tag: ''
      - aws-eks/create-cluster:
          cluster-name: << parameters.cluster-name >>
          node-type: t2.medium
          skip-kubectl-install: false
          nodes-min: 1
          nodes-max: 2

  create-deployment:
    docker:
      - image: cimg/python:3.7
    parameters:
      cluster-name:
        description: |
          Enter name of the EKS cluster
        type: string
        default: udacity-devpos-capstone-cluster
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: false
          resource-file-path: deployment.yaml
          resource-name: deployments/udacity-devpos-capstone-cluster

workflows:
  default:
    jobs:
      - docker-lint
      - docker-build:
          requires: [docker-lint]
      - create-cluster
      - create-deployment:
          requires: [create-cluster]