apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-devpos-trungtq7-project
  labels:
    app: udacity-devpos-trungtq7-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-devpos-trungtq7-project
  strategy:
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udacity-devpos-trungtq7-project
    spec:
      containers:
      - name: udacity-devpos-trungtq7-project
        imagePullPolicy: Always
        image: trungtq1991/udacity-aws-devops-capstone
        ports:
        - containerPort: 80