apiVersion: v1
kind: Service
metadata:
  name: udacity-devops-capstone-project
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: udacity-devops-capstone-project