apiVersion: v1
kind: Service
metadata:
  name: udacity-devpos-trungtq7-project
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: udacity-devpos-trungtq7-project