apiVersion: v1
kind: Service
metadata:
  name: devpos-capstone-project
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: devpos-capstone-project